### ISSUE TITLE
Data valumen not  accesible from Docker in osx

### ISSUE THREAD

**Issue by imanzano** [tobert/cassandra-docker#28]
Hi,

The run fails with

19:00:14,681 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/data/log/system.log,true) call failed. java.io.FileNotFoundException: /data/log/system.log (Permission denied)
        at java.io.FileNotFoundException: /data/log/system.log (Permission denied)
        at      at java.io.FileOutputStream.open(Native Method)
        at      at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
        at      at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:150)
        at      at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
        at      at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
        at      at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)

I just create the  data dir in my machine and run the script. It seems that osx and shared folder in docker does not work. 

It works if I don't specify the mount point for the volume. But Using that I will loose all the data every time I restart the container.

docker --version
Docker version 1.6.0, build 4749651

Any idea how to make it work ?

**Comment by imanzano** [comment]
It seams an issue with boot2docker and osx where the user permissions are not mapped. I'll close the issue.
